### ISSUE TITLE
USER STORY: Deploy Website

### ISSUE THREAD

**Issue by Alan-Bushell** [Alan-Bushell/la-cocina-del-diablo#1]
As a **developer** I can **deploy the website early** so that **I avoid any technical issues or stress closer to project submission.**

## Acceptance Criteria
 - The project must be deployed to Heroku
 - The project must use a 3rd party to host images like Cloudinary
 - The code must be stored in GitHub for the assessor to grade
 - The project must be displayed through my Github app

## Tasks
   - [x] Create workspace with Gitpod
   - [x] Connect Github to Heroku
   - [x] Set up environment variables
   - [x] Connect Cloudinary
   - [x] Ensure app is showing deployed on Heroku

**Comment by Alan-Bushell** [comment]
Add cloudinary to the tasks. Already present in acceptance creteria

**Comment by Alan-Bushell** [comment]
Issue with app showing as build successful on Heroku but once app was opened an application error was presented.

Contacted Tutor support where Ed spotted I had not added the App name to profile.

Updated this information and app was successfully deployed via Heroku.
