### ISSUE TITLE
USER STORY: Testing

### ISSUE THREAD

**Issue by Alan-Bushell** [Alan-Bushell/la-cocina-del-diablo#10]
As a **developer** I can **test the website** so that **the end product is free from errors and fit to go live**

## Acceptance Criteria
 - The logic and backend code should be tested and free from errors
 - The front end HTML and CSS should be tested and free from all errors
 - All links should work and point to their desired action
 - All images and aesthetic content should display in a clear and user friendly manner
 - The website passes at a high score through google Lighthouse
 - The deployed website displays as intended on partner hosting
 - All tests need to be documented in the readme either directly or in an intended tests file

## Tasks
   - [ ] Test backend code using Pep8 checker
   - [x] Test frontend code
   - [x] Test using google lighthouse
   - [x] Get new users to run through sample testing on website
     - [x] Collect results and score accordingly to success
     - [x] Add feedback from users regarding UI improvements
   - [x] Add all testing results and screenshots to Github repository

**Comment by Alan-Bushell** [comment]
PEP 8 checker is down so ran through all logic tests manually and added to readme.
