### ISSUE TITLE
USER STORY: Social Feed

### ISSUE THREAD

**Issue by Alan-Bushell** [Alan-Bushell/la-cocina-del-diablo#12]
As a **Business Owner** I can **display users social interactions** so that **potential customers can see real testimonials in a user friendly way.**

## Acceptance Criteria
 - The merchant should have twitter account
 - The merchant should be able to select the hashtag they want to display
 - The hashtag should pull the required data from twitter to display on the desired page

## Tasks
   - [x] Sign up for twitter developer console
   - [ ] Connect API and test pulled data
   - [ ] Display relevant tweet information ( user handle. tweet, image)

**Comment by Alan-Bushell** [comment]
Signed up for and have been approved for Twitter developer profile. 

Expecting to only need read only privileges for now.

As this is a nice to have and not mandatory I will not revisit unless the main project is completed in good time.
