### ISSUE TITLE
USER STORY: Create an account (CRUD)

### ISSUE THREAD

**Issue by Alan-Bushell** [Alan-Bushell/la-cocina-del-diablo#3]
As a **Customer** I can **Create an account** so that **I will have the ability to make a booking**

## Acceptance Criteria
 - User must provide all relevant basic information in being able make a booking. (Name, Phone, Email)
 - User should be able to login and log out once their account is created
 - User should have the ability to access a profile page that shows their account overview
 - User should have the ability to delete account

## Tasks
   - [x] Create backend profile logic (create backend)
   - [x] Add style and navigation to front end ( create functionality with HTML and CSS)
     - [x] Add icons if necessary for ease of use (Style to suit web theme)

**Comment by Alan-Bushell** [comment]
Installed allauth to allow for the creation of accounts. Basic functionality is in place but will update form to collect required data.

Basic user profile page also created. Will add user content and add crud functionality to allow user to amend if needed.

**Comment by Alan-Bushell** [comment]
created the template for the profile page in line with my wireframe. I wanted to have a base to work from so that I can test the booking / event ticket application I am currently building and wanted to be able to display it correctly.

Now that I have a base completed I will focus on adding the user model to the db, collect the required minimum info from a sign up form and then displaying that information on the users profile page.

From there it will be a case of allowing the user to make reservation requests with the restaurant and also booking tickets for the events pages.

Once that functionality is completed the bulk of the logic in the project will have been completed.

The last things to add is crud for user profile to change non mandatory info and the ability for management to create menus and programmatically display starters, mains and desserts for specific menus at the click of a button. 

Rather than having to manually type them in every time the menu changes they can select already added dishes to new menu lists and then display easily for customers on the front end.

**Comment by Alan-Bushell** [comment]
Users can create accounts and make a restaurant booking.

As of right now they have a profile page that just displays some placeholder information and some dynamic information unique to them.

Next steps will be allowing user to update their information with the site and add on delete functionality.
