### ISSUE TITLE
USER STORY: Base Template

### ISSUE THREAD

**Issue by Alan-Bushell** [Alan-Bushell/la-cocina-del-diablo#4]
As a **Developer** I can **view the website while coding it** so that **I can make adjustments and ensure a functionality works as expected.**

## Acceptance Criteria
 - Project must include a base template
 - Base template must have all required links, meta data and CDN's required for this project
 - Must include the links and navigation adhering to Django URL rules

## Tasks
   - [x] Create base.html & add boiler plate code
   - [x] Add links to static files like CSS & JS
   - [x] Add CDN links in Head

**Comment by Alan-Bushell** [comment]
Added boilerplate to project while working on back end to allow for testing. 

Boiler plate will be replaced when moving on to design phase.

**Comment by Alan-Bushell** [comment]
Changed Routing URLS as the base and index were injecting Events.html as the primary source. 

Updated this information and added the overarching restaurant app to look after the general info and user profile.

Added font awesome link to head of base to allow for profile icon to display.

Added style.css to style icon. Only minimal styling in place for time being.

**Comment by Alan-Bushell** [comment]
Amended the navbar and added and centered the main links I will be using for this project.

Anything above that would be aesthetical. 

Issue with the events url routing to events events/ instead of just events. 

Issue was resolved when I realized the error and removed the duplicate '/' link.
