### ISSUE TITLE
USER STORY: Make a Reservation

### ISSUE THREAD

**Issue by Alan-Bushell** [Alan-Bushell/la-cocina-del-diablo#5]
As a **Customer** I can **make a reservation** so that **I can dine at the venue**

## Acceptance Criteria
 - User must have an account to make a booking
 - User must have all required information on their profile(name, email, phone number)
 - Admin must be able to see the reservation on the backend to approve
 - User must be able to see reservation status from their profile

## Tasks
   - [x] Create booking Model (create backend)
   - [x] Create booking form ( create functionality with HTML and CSS)
   - [x] Add booking details to users profile
   - [x] Add notification for user once booking is accepted
     - [x] Add notification if not accepted

**Comment by Alan-Bushell** [comment]
Booking form now works and submits data to the database.

initial issue in pulling data from DB and displaying to user. could not prevent all users have access to all bookings.

This seems to be down to how I created my models. 

I have for now at least linked the booking by email address.

Current issue I am encountering is when the booking has been confirmed that it is not updating on the front end.

Will look into this at a later time as the notification side of things is not mandatory for right now.

**Comment by Alan-Bushell** [comment]
I have implemented a status change for the users profile page to let them know that a booking has been accepted or declined.

**Comment by Alan-Bushell** [comment]
User can edit reservation before it has been accepted.

User can also delete reservation at any stage

**Comment by Alan-Bushell** [comment]
While the fundamentals are completed I have not added a notification system once a booking is confirmed.

Will investigate Django signal emails to see if this can fulfill my goals.
