### ISSUE TITLE
USER STORY: Events

### ISSUE THREAD

**Issue by Alan-Bushell** [Alan-Bushell/la-cocina-del-diablo#6]
As a **Business owner** I can **showcase upcoming events** so that **users can reserve tickets**

## Acceptance Criteria
 - Users must have account
 - Events must open in a blog style page with image and content
 - If the event is over 30 days away then tickets cannot be reserved but a countdown time will be in its place.
 - If the event has allocated all of its tickets then it will show as sold out and not be able to be booked.
 - The admin must be able to view a list of attendees coming to the event
 - The user must be able to see the event in their bookings list from their profile
 - The user should be able to cancel their ticket if they can no longer attend and for it to return to the event portal.

## Tasks
   - [x] Create event models,  URLs and logic (create backend)
   - [x] Create event links and pages ( create functionality with HTML and CSS)
   - [ ] Add confirmed bookings to user profiles
   - [ ] Allow user to cancel tickets

**Comment by Alan-Bushell** [comment]
Added events modal and allowed admin ability to post new events and make them go live.

Added summer note to description field to allow for rich text editing.

**Comment by Alan-Bushell** [comment]
With the addition of the boilerplate html base templates the sample events are now showing as intended.

**Comment by Alan-Bushell** [comment]
The event details pages are now showing with the templated logic being injected for each individual item.

I need to add a ticket button for users to be able to request / reserve tickets.

I also want to add functionality for events where the tickets are not available to reserve until a certain date or time.

To achieve this I want to play around with some of the Django built-ins regarding date and time.

For now this will be left until the user model is created and a profile is set

**Comment by Alan-Bushell** [comment]
The longer I leave this feature the more I think it may not be necessary to include a ticket option.

For the basis of this project I am satisfied the requirements have been met and that all that remains is Extensive testing and general aesthetic improvements
