### ISSUE TITLE
USER STORY: Add or Edit Menu Items

### ISSUE THREAD

**Issue by Alan-Bushell** [Alan-Bushell/la-cocina-del-diablo#7]
As a **Manager** I can **Add, Edit or delete menu items** so that **we can offer specials to customers and use our excess stock**

## Acceptance Criteria
 - Manager should be able to edit Menu Item life on website either front end or back end
 - Manager should be able to save the information and for it to display in real time

## Tasks
   - [x] Create menu model and logic (create backend)
   - [x] Present menu in desired location on webpage 
   - [ ] Add CRUD to menu items

**Comment by Alan-Bushell** [comment]
Added the menu and dish models. 

Will revisit if I have time once the bulk of the logic is completed.

**Comment by Alan-Bushell** [comment]
While I have added the menu on the backend and it works perfectly, I have decided due to time constraint's I will not be adding a front end for the moment to allow business owner to perform live changes.

I will however add a specials model.
I will host it towards the bottom of the A la carte menu if time permits so if the biz owner wants to display specials they can.
