### ISSUE TITLE
USER STORY: Delete Profile (CRUD)

### ISSUE THREAD

**Issue by Alan-Bushell** [Alan-Bushell/la-cocina-del-diablo#9]
As a **customer** I can **delete my account** if **I no longer want to book at the restaurant**

## Acceptance Criteria
 - User needs to be able to click a delete account option
 - Defensive programming in place to prevent accidental deletion. (Modal)

## Tasks
   - [x] Create delete logic in backend
   - [x] Add delete account link to signed in user from profile page
   - [x] Style delete account button so it stands out with a warning red color to prevent accidental click
   - [x] Add pop up modal to confirm choice

**Comment by Alan-Bushell** [comment]
user can now delete their account through the profile page.

The click on the large red delete account button and then get prompted with a delete modal.

Once they select delete they are redirected back to the index / home page and a messages notification pops up letting them know the account has been deleted.
